version: '3.9'

services:

  mysql:
    image: mysql:8.4
    container_name: payment_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_gateway_db
      MYSQL_USER: kartikey
      MYSQL_PASSWORD: password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - payment-network

volumes:
  mysql_data:

networks:
  payment-network: